version: '2'

volumes:
  mysql_data:

services:

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  calculator.nginx:
    image: nginx:latest
    volumes:
      - ./run/sock:/sock
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www/calc-backend-storage:/usr/share/nginx/html/backend
      - ./www/calc-frontend-app:/usr/share/nginx/html/frontend
    ports:
      - '8080:8080'
      - '3000:3000'
    environment:
      TZ: Europe/Riga
    links:
      - calculator.fpm

  calculator.fpm:
    image: php-fpm
    build: ./
    volumes:
      - ./run/sock:/sock
      - ./php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./www/calc-backend-storage:/usr/share/nginx/html/backend
    environment:
      TZ: Europe/Riga
    links:
      - mysql
